'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cart_reminder
    Public Property id As Integer
    Public Property cart_id As Integer
    Public Property email_address As String
    Public Property email_content As String
    Public Property register_time As Date
    Public Property user_id As Integer

End Class
